main: fr.firedragonalex.plugintuto.Main
name: PluginTuto
version: 1.0
description: PluginTuto
api-version: 1.16
load: POSTWORLD
author: FireDragonAlex
commands:
  test:
    description: Ceci est une commande de test
    permission: test.use
  alert:
    description: Ceci permet de faire un broadcast custom
    permission: broadcast.use
  getstick:
    description: Ceci permet d'obtenir un baton avec un nom défini
    permission: getstick.use
  chestspawn:
    description: permet de faire apparaitre un coffre avec des items aléatoire
    permission: chestrandom.use
  roles:
    description: donne les roles
    permission: role.use
