package fr.firedragonalex.rankandlevels.rank;

public enum RankPermissions {
	
	RECEVEID_COSMETICS_TOKEN_LEVEL_2_AFTER_VOTING,
	CAN_USE_CRAFT_COMMAND,
	CAN_USE_FEED_COMMAND,
	RECEVEID_COSMETICS_TOKEN_LEVEL_2_AFTER_FINISHING_DAILY_QUESTS,
	RECEVEID_COSMETICS_TOKEN_LEVEL_1_OR_2_WHEN_LEVEL_UP,
	CAN_USE_ENDERCHEST_COMMAND,
	CAN_PLACE_1_TP_POINT_ON_THE_MAP,
	CAN_HAVE_MORE_HOUSES,
	CAN_HAVE_2_PETS,
	CAN_PLACE_2TP_POINT_ON_THE_MAP,
	CAN_HAVE_3_PETS,
	CAN_PLACE3_TP_POINT_ON_THE_MAP;

}
